name: D4RKO image
on:
  workflow_dispatch:
  push:
    paths:
      - images/win64/Dockerfile
      - .github/workflows/d4rko-image.yml
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: images/win64
          push: true
          tags: ghcr.io/0gmou/d4rko-win64:stable,ghcr.io/0gmou/d4rko-win64:latest
          provenance: false
          sbom: false
